server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # \u81EA\u5DF1\u4E0D\u5411Eureka\u4E2D\u6CE8\u518C\u81EA\u5DF1
    fetch-registry: false # \u4E0D\u5BFB\u627E\u5176\u4ED6\u7684\u5FAE\u670D\u52A1
    serviceUrl:
      # \u8BBF\u95EE\u7684\u65F6\u5019http://localhost:8761/\u53EF\u4EE5\u8BBF\u95EE\u5230
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
